version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticket-pg
    environment:
      POSTGRES_DB:       ticketdb
      POSTGRES_USER:     raksha
      POSTGRES_PASSWORD: ticket123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raksha -d ticketdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
